# ============================================
# = SERVER CONFIGURATION
# ============================================
spring.application.name=awesomepizza
server.port=8080

# ============================================
# = DATASOURCE CONFIGURATION
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/awesomepizza_db
spring.datasource.username=awesomepizza_admin
spring.datasource.password=awesomepizza_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# = JPA / HIBERNATE CONFIGURATION
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ============================================
# = SQL INITIALIZATION (data.sql)
# ============================================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# ============================================
# = Configurazione JWT
# ============================================
security.jwt.secret-key=f2f07e019cd749d1a96a22cf6f3f1bc5f9f4b0b18b75b7e5a617c1f1e9f4a22a
security.jwt.expiration=900000
security.jwt.refresh-expiration=604800000