# ============================================
# = SERVER CONFIGURATION
# ============================================
spring.application.name=awesomepizza
server.port=8080

# ============================================
# = DATASOURCE CONFIGURATION
# ============================================
spring.datasource.url=jdbc:postgresql://localhost:5432/awesomepizza_db
spring.datasource.username=awesomepizza_admin
spring.datasource.password=awesomepizza_pass
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================
# = JPA / HIBERNATE CONFIGURATION
# ============================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# ============================================
# = SQL INITIALIZATION (data.sql)
# ============================================
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true